# Generated by Django 5.1 on 2024-09-02 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('release_year', models.DateField(verbose_name='Дата выхода')),
                ('label', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('release_year', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('birth_day', models.DateField(verbose_name='Дата рождения')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Об исполнителе')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('date_foundation', models.DateField(verbose_name='Дата основания')),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='music.artist', verbose_name='Артисты')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='artist_groups', to='music.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название трека')),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Длительность')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_album', to='music.album', verbose_name='Альбом')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_artist', to='music.artist', verbose_name='Исполнитель')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre', verbose_name='Жанр')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_group', to='music.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='group_tracks', to='music.track', verbose_name='Треки'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='artist_tracks', to='music.track', verbose_name='Треки'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_group_name'),
        ),
    ]
